export const countryCodes = [
    { code: '+44', country: 'UK' },
    { code: '+33', country: 'France' },
    { code: '+49', country: 'Germany' },
    { code: '+39', country: 'Italy' },
    { code: '+34', country: 'Spain' },
    { code: '+41', country: 'Switzerland' },
    { code: '+43', country: 'Austria' },
    { code: '+45', country: 'Denmark' },
    { code: '+46', country: 'Sweden' },
    { code: '+47', country: 'Norway' },
    { code: '+31', country: 'Netherlands' },
    { code: '+32', country: 'Belgium' },
    { code: '+351', country: 'Portugal' },
    { code: '+352', country: 'Luxembourg' },
    { code: '+353', country: 'Ireland' },
    { code: '+354', country: 'Iceland' },
    { code: '+355', country: 'Albania' },
    { code: '+356', country: 'Malta' },
    { code: '+357', country: 'Cyprus' },
    { code: '+358', country: 'Finland' },
    { code: '+359', country: 'Bulgaria' },
    { code: '+36', country: 'Hungary' },
    { code: '+371', country: 'Latvia' },
    { code: '+372', country: 'Estonia' },
    { code: '+373', country: 'Moldova' },
    { code: '+374', country: 'Armenia' },
    { code: '+375', country: 'Belarus' },
    { code: '+376', country: 'Andorra' },
    { code: '+377', country: 'Monaco' },
    { code: '+378', country: 'San Marino' },
    { code: '+380', country: 'Ukraine' },
    { code: '+381', country: 'Serbia' },
    { code: '+382', country: 'Montenegro' },
    { code: '+383', country: 'Kosovo' },
    { code: '+385', country: 'Croatia' },
    { code: '+386', country: 'Slovenia' },
    { code: '+387', country: 'Bosnia and Herzegovina' },
    { code: '+389', country: 'North Macedonia' },
    { code: '+370', country: 'Lithuania' },
    { code: '+420', country: 'Czech Republic' },
    { code: '+421', country: 'Slovakia' },
    { code: '+423', country: 'Liechtenstein' },
    { code: '+48', country: 'Poland' },
    { code: '+40', country: 'Romania' },
    { code: '+20', country: 'Vatican City' },
  ]
  
 export const europeanCities = [
    'Amsterdam', 'Andorra la Vella', 'Antwerp', 'Athens', 'Barcelona', 'Belgrade', 'Berlin', 
    'Bratislava', 'Brussels', 'Bucharest', 'Budapest', 'Copenhagen', 'Dublin', 'Florence', 
    'Frankfurt', 'Genoa', 'Gothenburg', 'Hamburg', 'Helsinki', 'Krakow', 'Lisbon', 'Ljubljana', 
    'London', 'Luxembourg', 'Lyon', 'Madrid', 'Marseille', 'Milan', 'Monaco', 'Munich', 
    'Nicosia', 'Oslo', 'Paris', 'Podgorica', 'Porto', 'Prague', 'Reykjavik', 'Riga', 
    'Rome', 'Rotterdam', 'San Marino', 'Sarajevo', 'Skopje', 'Sofia', 'Stockholm', 
    'Stuttgart', 'Tallinn', 'The Hague', 'Thessaloniki', 'Turin', 'Valletta', 'Vienna', 
    'Vilnius', 'Warsaw', 'Zagreb', 'Zurich'
  ];
  